### ISSUE TITLE
Request Geolocation by browser

### ISSUE THREAD

**Issue by iesteban** [Semillas/semillas_backend#6]
It will be used afterwards in ReactJS to ask for the feed Endpoint to be done here:

https://github.com/Semillas/semillas_backend/issues/2

**Comment by Febrero** [comment]
Commit 24e6a225d953bcdeb573063b84a3199a82863511 and 88c46cbb2026594c606476a692e64c25177a98e7 have a prototype about this.
I need someone else check that in http://0.0.0.0:8000/webapp/geolocation, because of geolocation in my laptop is always `error.POSITION_UNAVAILABLE`, maybe for this bug: https://bugs.launchpad.net/linuxmint/+bug/1624937

**Comment by iesteban** [comment]
Amazing. I'm going to define the feature we were talking yesterday. If the user does not allow to give his location. Do not order the 'feed' by any location.

**Comment by iesteban** [comment]
I think we can close this right?

**Comment by Febrero** [comment]
Yes
